#!/usr/bin/env bash
pip3 install numpy
pip3 install scipy
pip3 install matplotlib
pip3 install Pillow
pip3 install ruamel.yaml
pip3 install mpmath
pip3 install dadi
pip3 install momi
pip3 install Cython
pip3 install networkx
pip3 install pandas
pip3 install demes
pip3 install h5py
pip3 install scikit-allel
pip3 install demesdraw
pip3 install git+https://bitbucket.org/simongravel/moments.git@moments
git clone https://bitbucket.org/simongravel/moments.git
cd moments
python setup.py build_ext --inplace
python setup.py install --ld_extensions
cd .. 
rm -r moments
pip3 install .
